package main

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func capture(t *testing.T, args ...string) string {
	t.Helper()

	outR, outW, err := os.Pipe()
	if err != nil {
		t.Fatal(err)
	}
	orig := os.Stdout
	os.Stdout = outW

	done := make(chan string)
	go func() {
		var b bytes.Buffer
		_, _ = b.ReadFrom(outR)
		done <- b.String()
	}()

	runErr := run(args)

	outW.Close()
	os.Stdout = orig
	out := <-done
	_ = outR.Close()

	if runErr != nil {
		t.Fatalf("run(%v) = %v", args, runErr)
	}
	return out
}

func TestJSONExportIsWellFormed(t *testing.T) {
	out := capture(t)

	var d dump
	if err := json.Unmarshal([]byte(out), &d); err != nil {
		t.Fatalf("export is not valid JSON: %v\n%s", err, out)
	}
	if d.Count != len(d.Techniques) || d.Count == 0 {
		t.Errorf("count %d does not match %d techniques", d.Count, len(d.Techniques))
	}
	if d.SchemaVersion == "" || d.Tool != "sixi-scanner" {
		t.Errorf("missing provenance: %+v", d)
	}
	for _, r := range d.Techniques {
		// A technique is sendable if it has either shape of payload. Checking only Variants would
		// have flagged the multi-turn techniques as broken rather than as a different shape.
		if r.ID == "" || r.Title == "" || len(r.Markers) == 0 ||
			(len(r.Variants) == 0 && len(r.Sequence) == 0) {
			t.Errorf("incomplete record: %+v", r)
		}
		for _, steps := range r.Sequence {
			if len(steps) == 0 {
				t.Errorf("empty sequence entry: %+v", r)
			}
		}
	}
}

// The entire point of the command is that two runs diff cleanly. Insertion
// order changes whenever anyone adds a technique anywhere, so an unsorted export
// would produce a whole-file diff for a one-line change.
func TestOutputIsSortedByID(t *testing.T) {
	out := capture(t)

	var d dump
	if err := json.Unmarshal([]byte(out), &d); err != nil {
		t.Fatal(err)
	}
	for i := 1; i < len(d.Techniques); i++ {
		if d.Techniques[i-1].ID >= d.Techniques[i].ID {
			t.Fatalf("not sorted at %d: %q then %q",
				i, d.Techniques[i-1].ID, d.Techniques[i].ID)
		}
	}
}

func TestExportIsDeterministic(t *testing.T) {
	if a, b := capture(t), capture(t); a != b {
		t.Error("two exports of the same catalogue differ; a diff would be noise")
	}
}

// Payloads contain angle brackets and ampersands by design. Escaping them turns
// the export into something a reviewer cannot read.
func TestJSONDoesNotEscapePayloads(t *testing.T) {
	out := capture(t, "--only", "probe.llm01.delimiter-injection")

	if strings.Contains(out, `&lt;`) || strings.Contains(out, `\u003c`) {
		t.Errorf("payloads were HTML-escaped:\n%s", out)
	}
	if !strings.Contains(out, `<|im_end|>`) {
		t.Errorf("the delimiter payload is not readable in the export:\n%s", out)
	}
}

func TestGoExportParsesBackAsTheSameData(t *testing.T) {
	out := capture(t, "--format", "go", "--only", "probe.llm02.system-prompt-leak")

	if !strings.Contains(out, "package technique") {
		t.Fatalf("not a Go source file:\n%s", out)
	}
	if !strings.Contains(out, "var CommunityTechniques = []Definition{") {
		t.Errorf("missing the slice declaration:\n%s", out)
	}

	// Every literal must be quoted. An unquoted string is the failure mode that
	// turns a reviewable file into a file that does not compile.
	if strings.Contains(out, `Description: Your`) || strings.Contains(out, `Variants:    [You`) {
		t.Errorf("an unquoted literal would not compile:\n%s", out)
	}

	// German and French payloads must survive as themselves, not as \u escapes.
	de := capture(t, "--format", "go", "--only", "probe.llm01.multilingual-bypass")
	if !strings.Contains(de, "Anweisungen") {
		t.Errorf("non-ASCII was escaped rather than preserved:\n%s", de)
	}
}

func TestGoExportNotesThatPayloadsAreAdversarial(t *testing.T) {
	out := capture(t, "--format", "go", "--only", "probe.llm01.instruction-override")
	if !strings.Contains(out, "adversarial prompts") {
		t.Errorf("the generated header does not warn a reader about the payloads:\n%s", out)
	}
	if !strings.Contains(out, "GENERATED by") {
		t.Errorf("the generated header does not say the file is generated:\n%s", out)
	}
}

func TestFiltersNarrowTheExport(t *testing.T) {
	var d dump
	if err := json.Unmarshal([]byte(capture(t, "--only", "probe.llm02.system-prompt-leak")), &d); err != nil {
		t.Fatal(err)
	}
	if d.Count != 1 || d.Techniques[0].ID != "probe.llm02.system-prompt-leak" {
		t.Errorf("--only did not narrow to one technique: %+v", d.Techniques)
	}

	if err := json.Unmarshal([]byte(capture(t, "--tag", "credentials")), &d); err != nil {
		t.Fatal(err)
	}
	if d.Count == 0 {
		t.Error("--tag matched nothing")
	}
	for _, r := range d.Techniques {
		if !strings.Contains(r.ID, "credential") && len(r.Tags) == 0 {
			t.Errorf("technique %s does not carry the requested tag", r.ID)
		}
	}

	if err := json.Unmarshal([]byte(capture(t, "--min-severity", "critical")), &d); err != nil {
		t.Fatal(err)
	}
	for _, r := range d.Techniques {
		if r.Severity != "critical" {
			t.Errorf("--min-severity critical returned a %s technique", r.Severity)
		}
	}
}

func TestBadInputIsRejectedRatherThanExportedEmpty(t *testing.T) {
	// A typo that produced an empty catalogue would look like a successful
	// export of nothing, which is the worst possible outcome for a sync.
	for _, args := range [][]string{
		{"--only", "probe.llm02.system-prompt-leak,typo.here"},
		{"--tag", "no-such-tag"},
		{"--min-severity", "apocalyptic"},
		{"--format", "xml"},
	} {
		if err := run(args); err == nil {
			t.Errorf("run(%v) succeeded; expected an error", args)
		}
	}
}

func TestCompareReportsAddedRemovedAndChanged(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "before.json")

	baseline := capture(t, "--only", "probe.llm02.system-prompt-leak,probe.llm06.tool-enumeration")
	if err := os.WriteFile(path, []byte(baseline), 0o600); err != nil {
		t.Fatal(err)
	}

	// One technique present in both, one only in the later dump.
	later := capture(t, "--only", "probe.llm02.system-prompt-leak")
	out := capture(t, "--compare", path, "--only", "probe.llm02.system-prompt-leak,probe.llm01.role-confusion")

	if !strings.Contains(out, "added    probe.llm01.role-confusion") {
		t.Errorf("added technique not reported:\n%s", out)
	}
	if !strings.Contains(out, "removed  probe.llm06.tool-enumeration") {
		t.Errorf("removed technique not reported:\n%s", out)
	}
	_ = later

	if !strings.Contains(out, "regression, not a diff to accept") {
		t.Errorf("a removal did not trigger the warning:\n%s", out)
	}
}

func TestCompareOnAnIdenticalCatalogueSaysNoChanges(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "before.json")
	if err := os.WriteFile(path, []byte(capture(t)), 0o600); err != nil {
		t.Fatal(err)
	}

	out := capture(t, "--compare", path)
	if !strings.Contains(out, "no changes") {
		t.Errorf("an unchanged catalogue did not report no changes:\n%s", out)
	}
}

func TestCompareIgnoresProseEdits(t *testing.T) {
	// Rewording a description is not a behavioural change. Flagging it would
	// train reviewers to skim past the output, which is the one thing this
	// command exists to prevent.
	a := record{ID: "x", Title: "T", Description: "old wording", Variants: []string{"p"}, Markers: []string{"m"}}
	b := a
	b.Description = "new wording, same meaning"

	if !unchanged(a, b) {
		t.Error("a prose-only edit was reported as a change")
	}

	c := a
	c.MinMarkers = 2
	if unchanged(a, c) {
		t.Error("a change to MinMarkers was not reported")
	}

	d := a
	d.Variants = []string{"p", "p2"}
	if unchanged(a, d) {
		t.Error("an added payload was not reported")
	}

	e := a
	e.Confidence = 0.9
	if unchanged(a, e) {
		t.Error("a confidence change was not reported")
	}
}

func TestCompareOnAMissingFileFailsLoudly(t *testing.T) {
	if err := run([]string{"--compare", filepath.Join(t.TempDir(), "absent.json")}); err == nil {
		t.Error("expected an error for a missing baseline")
	}
}
