package report

import (
	"fmt"
	"io"
	"strings"
	"time"

	"github.com/rbrus/sixi-scanner/internal/tech"
)

// WriteMarkdown writes the scan as a document a person can read and forward.
//
// It is the format to send to someone who has to decide whether to act. Every
// finding carries the prompt and the reply that produced it, because the
// question a reader has is always "show me".
func WriteMarkdown(w io.Writer, s *Scan) error {
	s.Summarise()

	var b strings.Builder

	fmt.Fprintf(&b, "# Scan report — %s\n\n", s.Target)
	fmt.Fprintf(&b, "**Tool** %s %s · **Finished** %s · **Attempts** %d\n\n",
		s.Tool, s.Version, s.FinishedAt.Format(time.RFC3339), s.Attempts)

	if len(s.TargetNotes) > 0 {
		b.WriteString("> **Scan-affecting settings**\n>\n")
		for _, n := range s.TargetNotes {
			fmt.Fprintf(&b, "> - %s\n", n)
		}
		b.WriteString("\n")
	}

	b.WriteString("## Summary\n\n")
	if len(s.Findings) == 0 {
		fmt.Fprintf(&b,
			"No findings. %d attempts across %d techniques found no confirmed break.\n\n"+
				"A clean report is evidence about the techniques that were run, not a "+
				"statement that the agent is secure. It does not cover techniques this "+
				"tool does not implement, and it does not cover attacks that need a "+
				"judgement no string match can make.\n\n",
			s.Attempts, len(s.Options.TechniqueIDs))
	} else {
		counts := s.CountBySeverity()
		fmt.Fprintf(&b, "| Severity | Findings |\n|---|---|\n")
		for _, sev := range []tech.Severity{
			tech.SeverityCritical, tech.SeverityHigh,
			tech.SeverityMedium, tech.SeverityLow, tech.SeverityInfo,
		} {
			if counts[sev] > 0 {
				fmt.Fprintf(&b, "| %s | %d |\n", title(sev), counts[sev])
			}
		}
		b.WriteString("\n")
	}

	for i, f := range s.Findings {
		fmt.Fprintf(&b, "## %d. %s\n\n", i+1, f.Title)
		fmt.Fprintf(&b, "| | |\n|---|---|\n")
		fmt.Fprintf(&b, "| **Severity** | %s |\n", title(f.Severity))
		fmt.Fprintf(&b, "| **Category** | %s |\n", f.Category)
		fmt.Fprintf(&b, "| **Confidence** | %.2f |\n", f.Confidence)
		fmt.Fprintf(&b, "| **Technique** | `%s` |\n", f.TechniqueID)
		fmt.Fprintf(&b, "| **Fingerprint** | `%s` |\n", f.Fingerprint)
		if len(f.Rounds) > 1 {
			fmt.Fprintf(&b, "| **Reproduced in** | %d rounds |\n", len(f.Rounds))
		}
		b.WriteString("\n")

		if f.Description != "" {
			fmt.Fprintf(&b, "%s\n\n", f.Description)
		}

		fmt.Fprintf(&b, "**Why this was judged a finding**\n\n%s\n\n", f.Evidence.Reason)

		b.WriteString("**Prompt sent**\n\n```\n")
		b.WriteString(trimBlock(f.Evidence.Prompt))
		b.WriteString("\n```\n\n")

		b.WriteString("**Reply received**\n\n```\n")
		b.WriteString(trimBlock(f.Evidence.Response))
		b.WriteString("\n```\n\n")

		if len(f.Evidence.Markers) > 0 {
			fmt.Fprintf(&b, "Matched markers: %s\n\n",
				codeList(f.Evidence.Markers))
		}
		if len(f.Evidence.Negated) > 0 {
			fmt.Fprintf(&b, "Discounted as mentions inside a denial: %s\n\n",
				codeList(f.Evidence.Negated))
		}
		if f.Remediation != "" {
			fmt.Fprintf(&b, "**Remediation**\n\n%s\n\n", f.Remediation)
		}
		b.WriteString("---\n\n")
	}

	fmt.Fprintf(&b,
		"### What this report is not\n\n"+
			"Generated by %s %s. Every finding above is a reproducible exchange "+
			"against the endpoint named at the top, and every one can be re-run with "+
			"`--only %s`. Nothing here is a certification, an attestation, or a "+
			"statement of compliance, and no output of this tool says the words "+
			"*compliant*, *certified* or *guaranteed*.\n",
		s.Tool, s.Version, firstOrNone(s.Options.TechniqueIDs))

	if _, err := io.WriteString(w, b.String()); err != nil {
		return fmt.Errorf("write Markdown: %w", err)
	}
	return nil
}

// trimBlock makes a prompt or reply safe to drop inside a fenced code block by
// neutralising any backticks that would close the fence early. An agent that
// echoes a fenced block back would otherwise break the report's own layout.
func trimBlock(s string) string {
	const fence = "```"
	for strings.Contains(s, fence) {
		s = strings.ReplaceAll(s, fence, "` ` `")
	}
	return s
}

func codeList(items []string) string {
	out := make([]string, 0, len(items))
	for _, i := range items {
		out = append(out, "`"+i+"`")
	}
	return strings.Join(out, ", ")
}

func title(s tech.Severity) string {
	if s == "" {
		return string(tech.SeverityInfo)
	}
	return strings.ToUpper(string(s[:1])) + string(s[1:])
}

func firstOrNone(ids []string) string {
	if len(ids) == 0 {
		return "(none)"
	}
	return ids[0]
}
